Feature sort by date and sort alphabatically
hpi-swa-teaching/RichClipboard pull request #33
Opened 2020-06-06 18:14 UTC by zortax

Closes #22 
Closes #29 
- [x] High Test-Coverage (90%), GUI Code might be an exception
- [ ] All Tests passing
- [ ] All files autoformatted (to be discussed)
- [ ] Codequality: not many long methods
- [ ] Codequality: Encapsulation (classes should be loosely coupled, law of demeter,...)
- [ ] Timetracking: Issue Timetracking is complete (Time spent)

2020-06-07 09:59 UTC, WolfgangDaniel requested changes

2020-06-07 09:59 UTC, WolfgangDaniel commented on RichClipboard.package/RCClippingsList.class/instance/applySort..st
> +		]
```suggestion
	" Private "
	^ sortBlock ifNil: [ 
			aCollection 
		] ifNotNil: [ 
			sortBlock value: aCollection 
		]
```

2020-06-08 22:21 UTC, jffjhnsn approved these changes

2020-06-09 04:55 UTC, WolfgangDaniel approved these changes

2020-06-09 09:39 UTC, merged