40 refractoring
hpi-swa-teaching/RichClipboard pull request #49
Opened 2020-06-27 09:55 UTC by SiddeshkanthLogonathan

Closes #40 

- [ ] High Test-Coverage (90%), GUI Code might be an exception
- [ ] All Tests passing
- [ ] All files autoformatted (to be discussed)
- [ ] Codequality: not many long methods
- [ ] Codequality: Encapsulation (classes should be loosely coupled, law of demeter,...)
- [ ] Timetracking: Issue Timetracking is complete (Time spent)

2020-06-27 10:00 UTC, SiddeshkanthLogonathan commented
**We haven't completed:**
1. Formatting all methods
2. Merging RCWindow and RCContextMenu

2020-07-05 14:07 UTC, jffjhnsn requested changes
Styling changes

2020-07-05 14:07 UTC, jffjhnsn commented on RichClipboard.package/RCClippingsList.class/instance/lastEventWasMouseEvent..st
> +	lastEventWasMouseEvent := aBool
```suggestion
lastEventWasMouseEvent: aBoolean
	lastEventWasMouseEvent := aBoolean
```

2020-07-05 14:07 UTC, jffjhnsn commented on RichClipboard.package/RCClippingsList.class/instance/selectedClippingIndex..st
>  	"At this moment we do not want any item to be selected"
```suggestion
	" At this moment we do not want any item to be selected "
	
```

2020-07-05 14:07 UTC, jffjhnsn commented on RichClipboard.package/RCClippingsList.class/instance/selectedClippingIndex..st
> +	(anIndex > 0 and: [self lastEventWasMouseEvent]) ifTrue: [
```suggestion
	(anIndex > 0 and: [ self lastEventWasMouseEvent ]) ifTrue: [
```

2020-07-05 14:07 UTC, jffjhnsn commented on RichClipboard.package/RCPluggableListMorph.class/instance/keyStroke..st
> +	super keyStroke: evt
```suggestion
keyStroke: anEvent 
	self listMorph lastEventWasMouseEvent: false.
	super keyStroke: anEvent
```

2020-07-05 14:07 UTC, jffjhnsn commented on RichClipboard.package/RCPluggableListMorph.class/instance/mouseUp..st
> +	super mouseUp: evt
```suggestion
mouseUp: anEvent
	self listMorph lastEventWasMouseEvent: true.
	super mouseUp: anEvent
```

2020-07-05 19:18 UTC, jffjhnsn approved these changes

2020-07-05 23:14 UTC, zortax approved these changes

2020-07-06 07:26 UTC, merged