47 update window title
hpi-swa-teaching/RichClipboard pull request #50
Opened 2020-06-28 16:11 UTC by SiddeshkanthLogonathan

Closes #47 
Closes #48 

- [ ] High Test-Coverage (90%), GUI Code might be an exception
- [ ] All Tests passing
- [ ] All files autoformatted (to be discussed)
- [ ] Codequality: not many long methods
- [ ] Codequality: Encapsulation (classes should be loosely coupled, law of demeter,...)
- [ ] Timetracking: Issue Timetracking is complete (Time spent)

2020-06-29 08:57 UTC, martingraf4 commented
Bevor ich reviewe @SiddeshkanthLogonathan  @WolfgangDaniel bitte erstmal die folgenden Bugs fixen:

1. wenn ich mehrmals auf "alphabetisch sortieren" oder "via Datum sortieren" klicke, wird der Titel einfach immer länger:
![image](https://user-images.githubusercontent.com/49309285/85993209-42adc800-b9f6-11ea-8269-87fcb1088999.png)
2. Bitte wenn ein neues Fenster geöffnet wird direkt die verwendete Sort-Order anzeigen (new-old):
![image](https://user-images.githubusercontent.com/49309285/85993336-7a1c7480-b9f6-11ea-93c1-58eb9981e73a.png)

Bevor ihr euch das Leben zu schwer macht:

Eine gute Idee das zu implementieren ist, 

1. eine Variable "usesDateSort" einzuführen, die angibt, ob nach Datum oder alphabetisch sortiert wird
2. sobald toggleDateSort (respektive toggleAlphabeticSort) aufgerufen wurde
  1. "usesDateSort" passend zu setzen
  2. updateWindowTitle aufzurufen
3. in updateWindowTitle anhand von privateModeActive (bereits implementiert), "usesDateSort" und "alphabeticSortInverted" (bzw. "dateSortInverted") zu setzen. Die Variablen xxxInverted haben ebenfalls schon den richtigen Wert

2020-06-29 09:03 UTC, martingraf4 commented
> 
> 
> Bevor ich reviewe @SiddeshkanthLogonathan @WolfgangDaniel bitte erstmal die folgenden Bugs fixen:
> 
>     1. wenn ich mehrmals auf "alphabetisch sortieren" oder "via Datum sortieren" klicke, wird der Titel einfach immer länger:
>        ![image](https://user-images.githubusercontent.com/49309285/85993209-42adc800-b9f6-11ea-8269-87fcb1088999.png)
> 
>     2. Bitte wenn ein neues Fenster geöffnet wird direkt die verwendete Sort-Order anzeigen (new-old):
>        ![image](https://user-images.githubusercontent.com/49309285/85993336-7a1c7480-b9f6-11ea-93c1-58eb9981e73a.png)
> 
> 
> Bevor ihr euch das Leben zu schwer macht:
> 
> Eine gute Idee das zu implementieren ist,
> 
>     1. eine Variable "usesDateSort" einzuführen, die angibt, ob nach Datum oder alphabetisch sortiert wird
> 
>     2. sobald toggleDateSort (respektive toggleAlphabeticSort) aufgerufen wurde
> 
>     3. "usesDateSort" passend zu setzen
> 
>     4. updateWindowTitle aufzurufen
> 
>     5. in updateWindowTitle anhand von privateModeActive (bereits implementiert), "usesDateSort" und "alphabeticSortInverted" (bzw. "dateSortInverted") zu setzen. Die Variablen xxxInverted haben ebenfalls schon den richtigen Wert

Das habt ihr zu großen Teilen schon so gemacht, aber ihr fügt da noch einigen unnötigen Code ein. z.B. wofür genau ist windowTitle wenn ihr sowieso schon currentSortMode habt?

Unter Umständen macht es Sinn, mit dem Wissen, die Features nochmal von vorne zu implementieren. Die Tests könnt ihr dabei natürlich übernehmen :). Ich vermute dann braucht ihr auch nicht länger als 20 Minuten und der Code ist am Ende wesentlich sauberer.

2020-06-29 13:39 UTC, SiddeshkanthLogonathan commented
@martingraf4, das Problem vor allem lag nicht am Code sondern beim Refractoring. Die Funktioniert jetzt aber die wird nochmal bearbeited.

2020-06-30 13:26 UTC, martingraf4 requested changes

2020-06-30 13:26 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/properties.json
> +		"windowTitle" ],
So wie ich das sehe haben wir diese Variable nur für die Tests hinzugfügt. Ich weiß nicht, ob ich das so schön finde. Schließlich repräsentiert diese Variable ja nicht, dass etwas angezeigt wird, sondern ist vollkommen unabhängig vom tatsächlichen Titel. Ich finde wir sollten die Variable rausschmeißen und den tatsächlichen Titel überprüfen (über self label oder in den Tests über window label)

2020-06-30 13:26 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/updateWindowTitle..st
> +	self setLabel: self windowTitle
Die Idee hinter der Methode "updateWindowTitle" ist (meiner Meinung nach), dass diese dafür verantwortlich ist, den Titel korrekt zu setzen (in welchen Randumständen auch immer) und somit von überall einfach aufgerufen werden kann. Darum ist es meiner Meinung nach sehr unpassend, dass ihr hier einen string als Parameter übergebt. Als Beispiel:

Der Fenstertitel verändert sich im Moment bei neuer Sortierordnung, und beim Private Mode (in Zukunft aber u.U. auch noch an anderen Stellen). An diesen Stellen sollten also einfach nur "self updateWindowTitle" aufgerufen werden müssen, ohne sich darum zu kümmern, irgendeinen String übergeben zu müssen oder darüber bescheid wissen zu müssen, wie der Titel intern aufgebaut ist.

2020-06-30 13:26 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/turnOnPrivateMode.st
>  	]
Warum macht ihr das so? Die Methode "self updateWindowTitle" sollte selbst dafür verantworlich sein, alles zu machen, was irgendwas mit dem Titel zu tun hat. Warum muss ich hier von außen noch "self windowTitle: ..." setzen?

Und wenn wir eh immer "self currentSortMode" als Parameter übergeben - warum ist das dann ein Parameter?

2020-06-30 13:26 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/toggleDateSort.st
>  	self fixHeightOfToolbarButtons
Meine Idee wäre ihr setzt in der Fallunterscheidung self currentSortMode auf 'old-new' oder what ever und wendet unten das ganze mit "self updateWindowTitle" an. Analog zu wie es bei privateMode war. (-> Das gleiche gilt auch für toggleAlphabeticSort)

2020-06-30 13:26 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/properties.json
> +		"windowTitle" ],
Ich sehe gerade, dass ihr die Variable anders benutzt habt, als ich es mir gedacht habe. Meiner Meinung nach sind eure aktuellen Tests allerdings nicht zielführend. Ihr solltet lieber überprüfen ob window label z.B. "(a-z)" beinhaltet, aber nicht "(z-a)".
Mit den aktuellen Tests überprüft ihr nur "steht in windowTitle das gleiche drin wie in window label". Und das für keinen Wert zum Produkt hinzu.

2020-06-30 18:52 UTC, martingraf4 requested changes

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindowTest.class/instance/testUpdateTitleAlphabeticallySorted.st
> +	Transcript show: window label.
Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/properties.json
> +		"windowTitle" ],
Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/windowTitle.st
> +	^ windowTitle
Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/windowTitle..st
> +	windowTitle := aString
Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/updateWindowTitle.st
> +		ifFalse: [self setLabel: self label, ''].
Diese Zeile brauchen wir nicht

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/updateWindowTitle..st
> +	self setLabel: self windowTitle
Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/turnOnPrivateMode.st
> +		self updateWindowTitle: self currentSortMode
```suggestion
		self updateWindowTitle
```
Die Variable wird oben schon gesetzt

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/privateModeActive..st
> +	privateModeActive := aBoolean
Hier darf es keinen Setter geben!! Die Variable "privateModeActive" wird direkt über "turnOn/OffPrivateMode" gesetzt. Wenn diese Methode von außen sichtbar ist, könnte man meinen man darf sie auch benutzen. Darf man aber nicht.

Also: Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/turnOffPrivateMode.st
> +		self updateWindowTitle.
```suggestion
		self clippingsList isInPrivateMode: false. 
		self updateWindowTitle
```
Das wird oben schon gesetzt

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/toggleDateSort.st
>  	self fixHeightOfToolbarButtons
Das "self updateWindowTitle" kann unten aufgerufen werden (und muss nicht in beiden Fallunterscheidungen einzeln hingeschrieben werden)

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/toggleAlphabeticSort.st
> +	self fixHeightOfToolbarButtons
Das "self updateWindowTitle" kann unten aufgerufen werden (und muss nicht in beiden Fallunterscheidungen einzeln hingeschrieben werden)

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/toggleAlphabeticSort.st
> +	self fixHeightOfToolbarButtons
Nachher die hinteren Punkte inn den Klammern noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/toggleDateSort.st
>  	self fixHeightOfToolbarButtons
Nachher die hinteren Punkte in den Klammern entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/setDefaultWindowTitle.st
> +	self setLabel: self windowTitle, ' (new-old)'
Bitte noch entfernen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/currentSortMode..st
> +	currentSortMode := aString
Auch hier bitte keinen öffentlichen Setter zur Verfügung stellen. Der Sortmode wird nämlich nicht angepasst, wenn dieser Setter benutzt wird. Das könnte man als Benutzer aber meinen.

Also: Bitte Methode entfernen und Refernzen durch direktes Setzen der Variable ersetzen

2020-06-30 18:52 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/initialize.st
> +	self setDefaultWindowTitle.
```suggestion
	self currentSortMode: ' (new-old)'.
	self updateWindowTitle.
```

2020-07-05 11:53 UTC, martingraf4 submitted a review, later dismissed

2020-07-05 16:12 UTC, martingraf4 approved these changes

2020-07-05 19:22 UTC, jffjhnsn approved these changes

2020-07-05 19:29 UTC, jffjhnsn commented
Merge after #49

2020-07-06 07:27 UTC, merged