41 documentation
hpi-swa-teaching/RichClipboard pull request #55
Opened 2020-07-05 22:38 UTC by jffjhnsn

Closes #41

- [x] Add class comments to all classes
- [x] Add [README.md](https://github.com/hpi-swa-teaching/RichClipboard/blob/41-documentation/README.md) with installation instructions, usage, etc.
- [x] Add [MIT license](https://github.com/hpi-swa-teaching/RichClipboard/blob/41-documentation/LICENSE.md)
- [ ] Add coding standards, etc. to [Wiki](https://github.com/hpi-swa-teaching/RichClipboard/wiki)

2020-07-06 08:05 UTC, martingraf4 requested changes

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +![CI](https://github.com/hpi-swa-teaching/RichClipboard/workflows/CI/badge.svg)
Ich würde die Badge noch umbenennen zu "Tests" (hier und in GitHub Actions)

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +
```suggestion
```
ist outdated

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +2. Run `RichClipboard default openInWorld` to set up the RichClipboard for the first time.
```suggestion
2. Run `RichClipboard default openInWorld` to set up RichClipboard for the first time.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +3. RichClipboard can be subsequently be opened by selecting `RichClipboard` from Apps-Menu.
```suggestion
3. RichClipboard can subsequently be opened by selecting `RichClipboard` from Apps-Menu.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +- In order to copy an entry back to RichClipboard, just click the desired entry and it will be deleted and re-copied back to the RichClipboard.
Diese Zeile finde ich etwas merkwürdig. Wie wäre es mit "Click on an entry to copy it back to the clipboard."

Wenn wir das so schreiben, verraten wir nämlich Implementation Details, was wir nicht sollten

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +- The last 5 copied entries are accessible by the RichClipboard Context-Menu. This is accessed by pressing `ctrl+v`.
```suggestion
- The last 5 copied entries are accessible by the RichClipboard Context-Menu. This is accessed by pressing `ctrl+alt+v`.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +  - Clicking `a-z` or `z-a` causes the entries to be sorted by ascending or descending alphabetical order and clicking `new-old` or `old-new` causes the entries to be sorted by the time it was copied
```suggestion
  - Clicking `a-z` or `z-a` causes the entries to be sorted by ascending or descending alphabetical order and clicking `new-old` or `old-new` causes the entries to be sorted by the time they were copied to RichClipboard.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +  - We can search for an entry or entries just by typing our desired word in the RichClipboard Window.
```suggestion
  - You can search for an entry or entries by typing the desired word into RichClipboard's window.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +  - In order to search for an entry or entries based on a certain pattern (Regex), click `Regex Search` and give in the desired pattern.
```suggestion
  - In order to search for an entry or entries based on a certain pattern (Regex), click `Regex Search` and type in the desired pattern.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +- Clicking `Toggle Private Mode` toggles between private mode and public mode. The important point is that in private mode, the copied entries will not be stored in RichClipboard.
```suggestion
- Clicking `Toggle Private Mode` toggles between private mode and default mode. In private mode, new clippings will not be stored in RichClipboard and clippings will disappear from the system clipboard after a few seconds.
```

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +  - To be able to determine whether RichClipboard is in private mode or not, look for the window title `(Private Mode)`. If it isn't present, that means that it isn't in private mode.
```suggestion
  - RichClipboard is in private mode if the suffix `(Private Mode)` is appended to the window title.
```

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCClippingsList.class/README.md
> +An RCClippingsList is a LazyListMorph used to display, sort and filter clippings as well as copy selected clippings back to the clipboard.
Bitte diesen Satz nochmal vereinfachen. Der ist zu lang und unverständlich.

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCClippingsList.class/README.md
> +	- The Squeak Clipboard object where clippings are copied to upon selection.
Kann meiner Meinung nach raus. Das ist sowieso nach zwei Issues wieder outdated und schadet mehr als es hilft (gilt auch für die anderen "Instance Variables" Teile.

Wenn jemand wissen will, was die Variablen sind, kann er auch kurz im Code nachgucken. Das Wichtige ist finde ich, dass klar wird, wo die Verantwortlichkeit der Klasse liegt.

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCClippingsList.class/README.md
> +	- The Squeak Clipboard object where clippings are copied to upon selection.
Und so eine Erklärung erweckt immer den Eindruck, dass sie vollständig ist, allerdings ist sie das (zumindest hier) nicht: systemClipboard kann nämlich z.B. auch ein NullObject sein.

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCClippingsList.class/README.md
> +An RCClippingsList is a LazyListMorph used to display, sort and filter clippings as well as copy selected clippings back to the clipboard.
```suggestion
An RCClippingsList is used to display, sort and filter clippings as well as copy selected clippings back to the clipboard.
```
Das sehen die Leute, dass das ein LazyListMorph ist (habe die Klasse auch unten immer ohne Kommentar raus genommen)

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/README.md
> +An RCClippingsWindow is a SystemWindow used to display stored clippings as well as present the user with a number of actions and options.
```suggestion
An RCClippingsWindow is used to display stored clippings as well as present the user with a number of actions and options.
```

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/README.md
> +An RCClippingsWindow is a SystemWindow used to display stored clippings as well as present the user with a number of actions and options.
Ich würde genauer werden. Statt "a number of actions and options" -> "contains a toolbar with options such as filter, sort or search".

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCContextMenu.class/README.md
> +An RCContextMenu allows the user to select one of their five most recent clippings to be pasted. It is opened by pressing `ctrl + alt + v` and the selected clipping is pasted upon being clicked.
```suggestion
An RCContextMenu allows the user to paste one of their five most recent clippings. It is opened by pressing `ctrl + alt + v`.
```

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCContextMenu.class/README.md
> +An RCContextMenu allows the user to select one of their five most recent clippings to be pasted. It is opened by pressing `ctrl + alt + v` and the selected clipping is pasted upon being clicked.
Vielleicht noch hinzufügen, dass es zu großen Teilen ein Duplikat von RCClippingsWindow ist? Das ist eine Information, die für die Weiterarbeit eines anderen Teams essentiell wäre

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCInvalidParameterError.class/README.md
> +An RCInvalidParameterError is an Error which is signaled if anything but a non-negative integer is used as an index when accessing an entry from RCStorage.
Finde ich unnötig. Der Name der Klasse spricht für sich

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCOutOfBoundsError.class/README.md
> +An RCOutOfBoundsError is an Error which is signaled upon attempted access of an index in RCStorage which is out of bounds.
Finde ich unnötig. Der Name der Klasse spricht für sich

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCPluggableListMorph.class/README.md
> +An RCPluggableListMorph enables interaction with the RCClippingsList in the RCClippingsWindow.
Würde noch genauer spezifizieren, was RCPluggableListMorph ist.

~Ist Counterpart zu RCClippingsList aka LazyListMorph + PluggableListMorph.
~Verantwortlich für die Systembrowser-ähnliche Suchfunktion (einfach in Fenster reintippen)

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCSearchBarMorph.class/README.md
> +An RCSearchBarMorph provides a text field for the user to type in a regex, which is used to filter the clippings.
Finde ich unnötig. Der Name der Klasse spricht für sich

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RCStorage.class/README.md
> +An RCStorage is a data structure used to store data copied to the clipboard.
Entweder weglassen oder genauer werden. Würde hier wenn dann darauf eingehen, dass RCStorage wirklich nur (dummer) Speicher ist und keine weitere Funktionalität hat, als Clippings zu speichern.

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RichClipboard.class/README.md
> +RichClipboard is a clipboard manager for Squeak which stores data copied to the clipboard to allow for further usage. It enhances the basic functions of cut, copy, and paste from the default clipboar
Würde hier 
```suggestion
RichClipboard is a clipboard manager for Squeak which stores clipboard entries (clippings) to allow for further usage. It enhances the basic functions of cut, copy, and paste from the default clipboard in Squeak.
```

2020-07-06 08:05 UTC, martingraf4 commented on RichClipboard.package/RichClipboard.class/README.md
> +
Würde noch einen Link zu unserer Git Seite hinzufügen

2020-07-06 08:05 UTC, martingraf4 commented on README.md
> +**RichClipboard** is a clipboard manager for Squeak which stores data copied to the clipboard to allow for further usage. It enhances the basic functions of cut, copy, and paste from the default clip
```suggestion
**RichClipboard** is a clipboard manager for Squeak which stores clipboard entries (clippings) to allow for further usage. It enhances the basic functions of cut, copy, and paste from the default clipboard in Squeak.
```

2020-07-21 10:37 UTC, jffjhnsn commented on RichClipboard.package/RCSearchBarMorph.class/README.md
> +An RCSearchBarMorph provides a text field for the user to type in a regex, which is used to filter the clippings.
Finde ich doch nötig, weil es nur für Regexes ist. Es ist nicht mit einer "normalen" SearchBar zu verwechseln. Oder wir benennen die Klasse zu RCRegexSearchBar um.

2020-07-21 14:54 UTC, martingraf4 submitted a review, later dismissed

2020-08-03 10:41 UTC, jffjhnsn commented
TODO: implement feedback from Luc (more detailed class comments which describe why certain design choices were made).

2020-08-03 15:48 UTC, martingraf4 approved these changes

2020-08-03 15:50 UTC, zortax approved these changes

2020-08-03 15:50 UTC, merged