58 consistent private mode
hpi-swa-teaching/RichClipboard pull request #60
Opened 2020-07-09 19:24 UTC by martingraf4

Closes #58 
Closes #59

- [ ] High Test-Coverage (90%), GUI Code might be an exception
- [ ] All Tests passing
- [ ] All files autoformatted (to be discussed)
- [ ] Codequality: not many long methods
- [ ] Codequality: Encapsulation (classes should be loosely coupled, law of demeter,...)
- [ ] Timetracking: Issue Timetracking is complete (Time spent)

2020-07-16 09:41 UTC, WolfgangDaniel submitted a review, later dismissed
Sieht gut aus.

2020-07-18 15:42 UTC, zortax requested changes
Keinen einzigen unnötigen Punkt am Methodenende gefunden.
![Impressive](https://media.makeameme.org/created/impressive-5b989c.jpg)

2020-07-18 15:42 UTC, zortax commented on RichClipboard.package/RCStorage.class/class/newWithRichClipboard..st
> +as yet unclassified
Kategorie fehlt (?)

2020-07-18 15:42 UTC, zortax commented on RichClipboard.package/RCStorage.class/class/newWithRichClipboard..st
> +	storage initialize.
Cascade? (muss in squeak gemacht werden wegen einrückungen)

2020-07-18 15:42 UTC, zortax commented on RichClipboard.package/RCStorageTest.class/instance/testSendsNotificationOnAddedItem.st
> +	storage add: storageItem.
Kaskade, falsche Einrückung

2020-07-18 15:42 UTC, zortax commented on RichClipboard.package/RichClipboard.class/instance/destroyContextMenu.st
> +		contextMenu removeActionsForEvent: #requestPasteClipping.
Kaskade?

2020-07-18 16:16 UTC, zortax approved these changes

2020-07-19 16:50 UTC, WolfgangDaniel approved these changes

2020-07-19 16:50 UTC, merged