56 clear one clipping
hpi-swa-teaching/RichClipboard pull request #61
Opened 2020-07-18 15:45 UTC by zortax

Closes #56 

- [ ] High Test-Coverage (90%), GUI Code might be an exception
- [ ] All Tests passing
- [ ] All files autoformatted (to be discussed)
- [ ] Codequality: not many long methods
- [ ] Codequality: Encapsulation (classes should be loosely coupled, law of demeter,...)
- [ ] Timetracking: Issue Timetracking is complete (Time spent)

2020-07-18 16:07 UTC, martingraf4 requested changes
Bevor ich detailliert reviewe müsst ihr noch einen Bug fixen:

Wenn ich im Moment einen Filter eingebe und dann ein Item lösche, wird das falsche Item gelöscht. Das Problem ist, dass die Clippings Liste unterschiedliche Indizes von dem Storage hat. Um das Problem zu umgehen empfehle ich euch, das Item per "item := clippingsList clippings at: anIndex" zu holen und dann via "storage remove: item" zu löschen. Dann braucht ihr auch die "removeAtIndex" Methode nicht mehr.

2020-07-21 14:38 UTC, jffjhnsn requested changes

2020-07-21 14:38 UTC, jffjhnsn commented on RichClipboard-Tests.package/RCClippingsListTest.class/instance/testRemoveAt.st
> +	storage add: 'hallo';
```suggestion
	storage add: 'hallo';
```

2020-07-21 14:38 UTC, jffjhnsn commented on RichClipboard.package/RCClippingsListTest.class/instance/testRemoveAt.st
> +	storage add: 'hallo';
```suggestion
	storage add: 'hallo';
```

2020-07-21 14:38 UTC, jffjhnsn commented on RichClipboard.package/RCPluggableListMorph.class/instance/closeItemMenuIfOpen.st
> +	].
```suggestion
	]
```

2020-07-21 14:38 UTC, jffjhnsn commented on RichClipboard.package/RCPluggableListMorph.class/instance/itemMenuFor..st
> +	itemMenu := MenuMorph new.
```suggestion
	itemMenu := MenuMorph new.
```

2020-07-21 14:38 UTC, jffjhnsn commented on RichClipboard.package/RCPluggableListMorph.class/instance/mouseDown..st
> +		menu := self  itemMenuFor: row.
```suggestion
		menu := self  itemMenuFor: row.
```

2020-07-21 15:11 UTC, martingraf4 requested changes

2020-07-21 15:11 UTC, martingraf4 commented on RichClipboard.package/RCClippingsWindow.class/instance/addClippingsList.st
> +	pluggableListMorph := RCPluggableListMorph newWithClippingsList: (self clippingsList) deleteCallback: #removeAt: on: (self clippingsList).
Würde ich in RCPluggableListMorph einfach hardcoden glaube ich. Oder seht ihr irgendeinen Anwendungsfall wo wir removeAt an ein anderes Objekt senden oder wir sogar eine andere Methode aufrufen?

(Der Konstruktor sollte so sein wie vorher)

2020-07-21 15:11 UTC, martingraf4 commented on RichClipboard.package/RCContextMenu.class/instance/addClippingsList.st
> +	pluggableListMorph := RCPluggableListMorph newWithClippingsList: (self clippingsList) deleteCallback: #removeAtIndex: on: (self storage).
Wenn wir das hardcoden können wir nämlich auch nicht vergessen die Referenz zu updaten und senden es nicht aus Versehen an das falsche Objekt :)

2020-07-21 15:11 UTC, martingraf4 commented on RichClipboard.package/RCPluggableListMorph.class/instance/itemMenuFor..st
> +				selector: (self deleteCallback)
hier direkt `target: self listMorph` verwenden. Dann brauchen wir die beiden Instanzvariablen auch nicht

2020-07-21 15:11 UTC, martingraf4 commented on RichClipboard.package/RCPluggableListMorph.class/instance/mouseUp..st
> -	self listMorph lastEventWasMouseEvent: true.
Diese Zeile darf nicht gelöscht werden. Sonst entstehen Probleme wenn man gleichzeitig tippt und klickt

2020-07-21 15:11 UTC, martingraf4 commented on RichClipboard.package/RCPluggableListMorph.class/properties.json
> +		"deleteCallbackObject",
Weg damit

2020-07-21 16:01 UTC, martingraf4 requested changes
Es muss darüber hinaus noch ein Bug gefixt werden:
Bei der Suche von Clippings + Rechtsklick delete wird manchmal das falsche gelöscht.

Fix: Benutzt stattdessen `self itemAt: index` im PluggableListMorph

Refactorings:
- Entfernt die ganzen "removeAt:" Methoden
- Fügt eine "remove" Methode zu den RC Storage Items hinzu
- Ersetzt die "remove: item" Methode vom storage durch "item remove"
- Merged Master rein

2020-08-03 10:02 UTC, jffjhnsn requested changes
Just a small refactoring for the tests.

2020-08-03 10:02 UTC, jffjhnsn commented on RichClipboard-Tests.package/RCPluggableListMorphTest.class/instance/testRightClickOnListItem.st
> +	pluggableListMorph := RCPluggableListMorph newWithClippingsList: clippingsList.
Instead of initializing these in all 3 tests in `RCPluggableListMorphTest`, they can be integrated into the setup method using the test instance of RichClipboard. `RCClippingsListTest` and `RCClippingsWindowTest` are examples of how this could be done.

2020-08-03 10:02 UTC, jffjhnsn commented on RichClipboard-Tests.package/RCPluggableListMorphTest.class/instance/testRightClickOnListItem.st
> +	pluggableListMorph := RCPluggableListMorph newWithClippingsList: clippingsList.
Just noticed that `clippingsList` and `pluggableListMorph` are instance variables (and initialized in `setup`) but are never used. So in summary, these 2 instance vars should be used in all tests and a new instance variable should be added for storage, initialized with `storage := richClipboard storage` in `setup`

2020-08-03 13:26 UTC, martingraf4 approved these changes

2020-08-03 13:34 UTC, jffjhnsn approved these changes

2020-08-03 13:34 UTC, merged